### ISSUE TITLE
Running tasks are not cancelled without the `ev` extension

### ISSUE THREAD

**Issue by nilmerg** [Icinga/ipl-scheduler#33]
* Disable the extension or don't have it installed in the first place
* Run the unit tests
* `SchedulerTest::testCancelingRunningTasks()` will not succeed

So, either the extension is not only *suggested* (i.e. required) or the implementation accounts for both cases.

**Comment by yhabteab** [comment]
This only affects the unit tests but the actual scheduler implementation works with and without this extension. So I don't know whether this is a valuable reason to require the extension.
